workflows:
  chofly-android:
    name: CHOFLY Android Build

    environment:
      flutter: stable

    scripts:
      - name: Flutter pub get
        script: flutter pub get

      - name: Fix AndroidX
        script: |
          echo "android.useAndroidX=true" >> android/gradle.properties
          echo "android.enableJetifier=true" >> android/gradle.properties

      - name: Build APK
        script: flutter build apk --release

    artifacts:
      - build/**/outputs/**/*.apk
